sudo: false
language: elixir
elixir:
  - 1.6
  - 1.7
  - 1.8.1
  - 1.9.0
otp_release:
  - 19.0
  - 20.3
  - 21.0
  - 22.0

matrix:
  exclude:
  - otp_release: 22.0
    elixir: 1.6
  - otp_release: 19 
    elixir: 1.8.1
  - otp_release: 19
    elixir: 1.9.0 
## https://github.com/hexpm/hexpm/issues/831

script:
  - "mix format --check-formatted --dry-run"
  - "MIX_ENV=test mix do deps.get, test"
